<?php
/**
 * Copyright Wikula Team 2011
 *
 * This work is contributed to the Zikula Foundation under one or more
 * Contributor Agreements and licensed to You under the following license:
 *
 * @license GNU/GPLv3 (or at your option, any later version).
 * @package Wikula
 * @link https://github.com/phaidon/Wikula
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

/**
 * A menu block.
 * 
 * @package Wikula
 */
class Wikula_Block_Menu extends Zikula_Controller_AbstractBlock
{

    /**
     * Initialise block.
     *
     * @return void
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('Wikula:menublock:', 'Block title::');
    }

    /**
     * Get information on block.
     *
     * @return array The block information
     */
    public function info()
    {
        return array(
            'text_type'       => $this->__('menu'),
            'text_type_long'  => $this->__('Wikula Menu Page'),
            'module'          => 'Wikula',
            'allow_multiple'  => true,
            'form_content'    => false,
            'form_refresh'    => false,
            'admin_tableless' => true,
            'show_preview'    => true
        );
    }

    /**
     * Display block.
     *
     * @param array $blockInfo A blockinfo structure.
     *
     * @return string|void The rendered block.
     */
    public function display($blockinfo)
    {
        if (!SecurityUtil::checkPermission('Wikula:menublock', $blockinfo['title'].'::', ACCESS_READ)) {
            return false;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = array($this->__('HomePage'));
        }

        // Check if the Wikula module is available. 
        if (!ModUtil::available('Wikula')) {
            return false;
        }

        $this->view->assign('pages', $vars['menupages']);

        $content = $this->view->fetch('block/menu.tpl');

        // Populate block info and pass to theme
        $blockinfo['content'] = $content;
        return BlockUtil::themeBlock($blockinfo);
    }

    /**
     * Modify block settings
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the bock form
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = array($this->__('HomePage'));
        }
                
        $pages = ModUtil::apiFunc($this->name, 'user', 'LoadAllPages');
        $this->view->assign('pages', $pages);
        
        // assign the approriate values
        $this->view->assign('menupages', $vars['menupages']);

        // Return the output that has been generated by this function
        return $this->view->fetch('block/menu_modify.tpl');
    }

    /**
     * Update block settings
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       $blockinfo  the modified blockinfo structure
     */
    public function update($blockinfo)
    {
        $test = FormUtil::getPassedValue('test');
        $test = implode(",", $test);
        LogUtil::registerStatus($test);
        
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['menupages'] = FormUtil::getPassedValue('menupages');

            // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $this->view->clear_cache('block/menu.tpl');

        return $blockinfo;
    }
}