<?php
/**
 * Wikula
 *
 * @copyright  (c) Wikula Development Team
 * @link       https://github.com/phaidon/Wikula/
 * @license    GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 */

class Wikula_Block_Menu extends Zikula_Controller_AbstractBlock
{

    /**
     * Initialise block
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('Wikula:menublock:', 'Block title::');
    }

    /**
     * Get information on block
     * 
     * @return       array       The block information
     */
    public function info()
    {
        return array(
            'text_type'       => $this->__('menu'),
            'text_type_long'  => $this->__('Wikula Menu Page'),
            'module'          => 'Wikula',
            'allow_multiple'  => true,
            'form_content'    => false,
            'form_refresh'    => false,
            'admin_tableless' => true,
            'show_preview'    => true
        );
    }

    /**
     * Display block
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the rendered bock
     */
    public function display($blockinfo)
    {
        if (!SecurityUtil::checkPermission('Wikula:menublock', $blockinfo['title'].'::', ACCESS_READ)) {
            return false;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = $this->__('HomePage');
        }

        // Check if the Wikula module is available. 
        if (!ModUtil::available('Wikula')) {
            return false;
        }

        $this->view->assign('pages', explode(",", $vars['menupages']));

        $content = $this->view->fetch('block/menu.tpl');

        // Populate block info and pass to theme
        $blockinfo['content'] = $content;
        return BlockUtil::themeBlock($blockinfo);
    }

    /**
     * Modify block settings
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the bock form
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = 'HomePage';
        }

        // assign the approriate values
        $this->view->assign('menupages', $vars['menupages']);

        // Return the output that has been generated by this function
        return $this->view->fetch('block/menu_modify.tpl');
    }

    /**
     * Update block settings
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       $blockinfo  the modified blockinfo structure
     */
    public function update($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['menupages'] = FormUtil::getPassedValue('menupages');

            // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $this->view->clear_cache('block/menu.tpl');

        return $blockinfo;
    }
}