<?php
/**
 * Wikula
 *
 * @copyright  (c) Wikula Development Team
 * @link       https://github.com/phaidon/Wikula/
 * @license    GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 */

class Wikula_Block_Menu extends Zikula_Controller_AbstractBlock
{

    /**
     * initialise block
     * 
     * @author       The PostNuke Development Team
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('Wikula:menublock:', 'Block title::');
    }

    /**
     * get information on block
     * 
     * @author       The PostNuke Development Team
     * @return       array       The block information
     */
    public function info()
    {
        return array(
            'text_type'      => 'menu',
            'module'         => 'Wikula',
            'text_type_long' => 'Show Wikula menu page',
            'allow_multiple' => true,
            'form_content'   => false,
            'form_refresh'   => false,
            'show_preview'   => true
        );
    }

    /**
     * display block
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the rendered bock
     */
    public function display($blockinfo)
    {
        if (!SecurityUtil::checkPermission('Wikula:menublock', $blockinfo['title'].'::', ACCESS_READ)) {
            return;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = $this->__('HomePage');
        }

        // Check if the Wikula module is available. 
        if (!ModUtil::available('Wikula')) {
            return false;
        }



        $render = pnRender::getInstance('Wikula');

        $render->assign('pages', explode(",", $vars['menupages']));

        $content = $render->fetch('block/menu.tpl');

        // Populate block info and pass to theme
        $blockinfo['content'] = $content;
        return BlockUtil::themesideblock($blockinfo);
    }

    /**
     * modify block settings
     * 
     * @author       The PostNuke Development Team
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the bock form
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['menupages'])) {
            $vars['menupages'] = 'HomePage';
        }

        // Create output object
        // As Admin output changes often, we do not want caching.
        $render = pnRender::getInstance('Wikula', false);

        // assign the approriate values
        $render->assign('menupages', $vars['menupages']);

        // Return the output that has been generated by this function
        return $render->fetch('block/menu_modify.tpl');
    }

    /**
     * update block settings
     * 
     * @param        array       $blockinfo     a blockinfo structure
     * @return       $blockinfo  the modified blockinfo structure
     */
    public function update($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['menupages'] = FormUtil::getPassedValue('menupages');

            // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $render = pnRender::getInstance('Wikula');
        $render->clear_cache('block/menu.tpl');

        return $blockinfo;
    }
}