<?php

/**
 * Copyright Wikula Team 2011
 *
 * This work is contributed to the Zikula Foundation under one or more
 * Contributor Agreements and licensed to You under the following license:
 *
 * @license GNU/GPLv3 (or at your option, any later version).
 * @package Piwik
 * @link https://github.com/phaidon/Wikula
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

class Wikula_Block_RecentChanges extends Zikula_Controller_AbstractBlock
{
    /**
     * initialise block
     *
     * @author       Mateo Tibaquirá
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('wikula:recentchangesblock:', 'Block ID::');
    }

    /**
     * get information on block
     *
     * @author       Mateo Tibaquirá
     * @return       array       The block information
     */
    public function info()
    {
        return array('text_type'      => 'recentchanges',
                     'module'         => 'wikula',
                     'text_type_long' => 'Show the wikula recent changes',
                     'allow_multiple' => false,
                     'form_content'   => false,
                     'form_refresh'   => false,
                     'show_preview'   => true);
    }

    /**
     * display block
     *
     * @author       Mateo Tibaquirá
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the rendered bock
     */
    public function display($blockinfo)
    {
        $dom = ZLanguage::getModuleDomain('Wikula');
        if (!SecurityUtil::checkPermission('Wikula:recentchangesblock', $blockinfo['bid'].'::', ACCESS_READ)) {
            return;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['numitems'])) {
            $vars['numitems'] = 5;
        }

        // Check if the wikula module is available.
        if (!ModUtil::available('Wikula')) return false;

        $pages = ModUtil::apiFunc('Wikula', 'user', 'LoadRecentlyChanged',
                              array('numitems' => $vars['numitems']));

        if (!$pages) {
            return __('There are no recent changes', $dom);
        }

        $curday = '';
        $pagelist = array();
        foreach ($pages as $page)
        {
            list($day, $time) = explode(' ', $page['time']);
            if ($day != $curday) {
                $dateformatted = date(__('D, d M Y', $dom), strtotime($day));
                $curday = $day;
            }

            if ($page['user'] == System::getVar('anonymous')) {
                $page['user'] .= ' ('.__('anonymous user', $dom).')'; // anonymous user
            }

            $pagelist[$dateformatted][] = $page;
        }
        unset($pages);

        $render = pnRender::getInstance('Wikula', false);
        $render->assign('pagelist', $pagelist);

        // Populate block info and pass to theme
        $blockinfo['content'] = $render->fetch('block/recentchanges.tpl');
        return BlockUtil::themesideblock($blockinfo);
    }


    /**
     * modify block settings
     *
     * @author       Mateo Tibaquirá
     * @param        array       $blockinfo     a blockinfo structure
     * @return       output      the bock form
     */
    public function modify($blockinfo)
    {
        $dom = ZLanguage::getModuleDomain('wikula');
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['numitems'])) {
            $vars['numitems'] = 5;
        }

        // Create output object
            // As Admin output changes often, we do not want caching.
        $render = pnRender::getInstance('wikula', false);

        // assign the approriate values
        $render->assign('blockvars', $vars);

        // Return the output that has been generated by this function
        return $render->fetch('block/recentchanges_modify.tpl');
    }


    /**
     * update block settings
     *
     * @author       Mateo Tibaquirá
     * @param        array       $blockinfo     a blockinfo structure
     * @return       $blockinfo  the modified blockinfo structure
     */
    public function update($blockinfo)
    {
        $dom = ZLanguage::getModuleDomain('wikula');
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['numitems'] = FormUtil::getPassedValue('numitems', 5);

        // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $render = pnRender::getInstance('wikula');
        $render->clear_cache('block/recentchanges.tpl');

        return $blockinfo;
    }
}
