<?php
/**
 * Copyright Wikula Team 2011
 *
 * @license GNU/GPLv3 (or at your option, any later version).
 * @package Wikula
 * @link https://github.com/phaidon/Wikula
 *
 * Please see the NOTICE file distributed with this source code for further
 * information regarding copyright and licensing.
 */

/**
 * A RecentChanges block.
 */
class Wikula_Block_RecentChanges extends Zikula_Controller_AbstractBlock
{
    /**
     * Initialise block.
     *
     * @return void
     */
    public function init()
    {
        // Security
        SecurityUtil::registerPermissionSchema('Wikula:recentchangesblock:', 'Block ID::');
    }

    /**
     * Get information on block.
     *
     * @return array The block information
     */
    public function info()
    {
        return array('text_type'       => $this->__('recentchanges'),
                     'text_type_long'  => $this->__('Wikula Recent Changes'),
                     'module'          => 'Wikula',
                     'allow_multiple'  => false,
                     'form_content'    => false,
                     'form_refresh'    => false,
                     'admin_tableless' => true,
                     'show_preview'    => true);
    }

    /**
     * Display block.
     *
     * @param array $blockinfo A blockinfo structure.
     *
     * @return string|void The rendered block.
     */
    public function display($blockinfo)
    {
        if (!SecurityUtil::checkPermission('Wikula:recentchangesblock', $blockinfo['bid'].'::', ACCESS_READ)) {
            return false;
        }

        // Get variables from content block
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['numitems'])) {
            $vars['numitems'] = 5;
        }

        // Check if the wikula module is available. 
        if (!ModUtil::available('Wikula')) {
            return false;
        }

        $pages = ModUtil::apiFunc('Wikula', 'user', 'LoadRecentlyChanged', array('numitems' => $vars['numitems']));

        if (!$pages) {
            return $this->__('There are no recent changes');
        }

        $curday = '';
        $pagelist = array();
        foreach ($pages as $page) {
            if ($page['time']->getTimestamp() != $curday) {
                $dateformatted = $page['time']->format('D, d M Y');
                $curday = $page['time']->getTimestamp();
            }

            if ($page['user'] == System::getVar('anonymous')) {
                $page['user'] .= ' ('.$this->__('anonymous user').')'; // anonymous user
            }

            $pagelist[$dateformatted][] = $page;
        }
        unset($pages);

        $this->view->assign('pagelist', $pagelist);

        // Populate block info and pass to theme
        $blockinfo['content'] = $this->view->fetch('block/recentchanges.tpl');
        return BlockUtil::themeBlock($blockinfo);
    }


    /**
     * modify block settings
     *
     * @param array $blockinfo A blockinfo structure.
     * 
     * @return output The bock form
     */
    public function modify($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // Defaults
        if (empty($vars['numitems'])) {
            $vars['numitems'] = 5;
        }

        // assign the approriate values
        $this->view->assign('blockvars', $vars);

        // Return the output that has been generated by this function
        return $this->view->fetch('block/recentchanges_modify.tpl');
    }


    /**
     * update block settings
     *
     * @param array $blockinfo A blockinfo structure.
     * 
     * @return $blockinfo The modified blockinfo structure.
     */
    public function update($blockinfo)
    {
        // Get current content
        $vars = BlockUtil::varsFromContent($blockinfo['content']);

        // alter the corresponding variable
        $vars['numitems'] = FormUtil::getPassedValue('numitems', 5);

        // write back the new contents
        $blockinfo['content'] = BlockUtil::varsToContent($vars);

        // clear the block cache
        $this->view->clear_cache('block/recentchanges.tpl');

        return $blockinfo;
    }
}
